"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const sectors = ["technology", "engineering", "business", "finance"] as const;
type ExistingProfile = { profile?: { current_stage?: "Year 12" | "Year 13"; application_cycle?: number; home_region?: string; max_travel_minutes?: number; relocation_preference?: "stay-local" | "could-relocate" | "unsure"; route_intent?: "university" | "apprenticeship" | "combined"; sectors?: string[]; work_styles?: string[]; financial_preference?: "open" | "cost-aware" | "prefer-lower-debt"; constraints?: string[]; experience_summary?: string; qualifications_complete?: boolean; } | null; qualifications?: Array<{ id: string; qualification_type: string; subject: string; grade?: string; status: "predicted" | "achieved" | "unknown" }>; };
type QualificationRow = { id?: string; qualificationType: string; subject: string; grade: string; status: "predicted" | "achieved" | "unknown"; };
function blankQualification(): QualificationRow { return { qualificationType: "A level", subject: "", grade: "", status: "predicted" }; }

export function ReadinessForm() {
  const router = useRouter();
  const [existing, setExisting] = useState<ExistingProfile | null>(null);
  const [selectedSectors, setSelectedSectors] = useState<string[]>([]);
  const [qualifications, setQualifications] = useState<QualificationRow[]>([]);
  const [qualificationsComplete, setQualificationsComplete] = useState<boolean | null>(null);
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    void fetch("/api/analytics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventName: "readiness_started", properties: {} }) });
    fetch("/api/profile").then((response) => response.json()).then((data: ExistingProfile) => {
      setExisting(data); setSelectedSectors(data.profile?.sectors ?? []);
      setQualifications((data.qualifications ?? []).map((qualification) => ({ id: qualification.id, qualificationType: qualification.qualification_type, subject: qualification.subject, grade: qualification.grade ?? "", status: qualification.status })));
      setQualificationsComplete(data.profile ? (data.profile.qualifications_complete ?? false) : null);
    }).catch(() => setExisting({}));
  }, []);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMessage("");
    const form = new FormData(event.currentTarget);
    const payload = { currentStage: form.get("currentStage"), applicationCycle: Number(form.get("applicationCycle")), homeRegion: form.get("homeRegion"), maxTravelMinutes: Number(form.get("maxTravelMinutes")), relocationPreference: form.get("relocationPreference"), routeIntent: form.get("routeIntent"), sectors: selectedSectors, workStyles: String(form.get("workStyles") ?? "").split(",").map((value) => value.trim()).filter(Boolean), financialPreference: form.get("financialPreference"), constraints: String(form.get("constraints") ?? "").split("\n").map((value) => value.trim()).filter(Boolean), experienceSummary: form.get("experienceSummary") || undefined, qualifications: qualifications.map((qualification) => ({ ...(qualification.id ? { id: qualification.id } : {}), qualificationType: qualification.qualificationType, subject: qualification.subject, ...(qualification.status === "unknown" ? {} : { grade: qualification.grade }), status: qualification.status })), qualificationsComplete: qualificationsComplete ?? false, policyVersion: "2026-07-29" };
    const response = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) { setMessage(result.error?.message ?? "Check your answers and try again."); setSaving(false); return; }
    router.push("/strategy"); router.refresh();
  }
  if (!existing) return <p role="status" className="rounded-2xl bg-white p-6 font-semibold">Loading your saved progress…</p>;
  const profile = existing.profile;
  const field = "mt-2 min-h-12 w-full rounded-2xl border border-ink/15 bg-white px-4 py-3 font-semibold outline-none focus:border-leaf focus:ring-4 focus:ring-leaf/10";
  const updateQualification = (index: number, update: Partial<QualificationRow>) => { setQualifications((current) => current.map((qualification, rowIndex) => rowIndex === index ? { ...qualification, ...update } : qualification)); };
  return (
    <form onSubmit={submit} className="space-y-6">
      <section className="grid gap-5 rounded-[2rem] bg-white/80 p-5 shadow-sm sm:grid-cols-2 sm:p-7">
        <label className="font-black">Current stage<select name="currentStage" defaultValue={profile?.current_stage ?? "Year 12"} className={field}><option>Year 12</option><option>Year 13</option></select></label>
        <label className="font-black">Application cycle<select name="applicationCycle" defaultValue={profile?.application_cycle ?? 2027} className={field}>{[2027, 2028, 2029, 2030, 2031, 2032].map((year) => <option key={year}>{year}</option>)}</select></label>
        <label className="font-black">Broad home area<input name="homeRegion" required minLength={2} defaultValue={profile?.home_region ?? ""} placeholder="For example: West Midlands" className={field} /><span className="mt-2 block text-xs font-semibold text-ink/50">Do not enter your full address or postcode.</span></label>
        <label className="font-black">Maximum one-way travel time<input name="maxTravelMinutes" type="number" min="0" max="360" defaultValue={profile?.max_travel_minutes ?? 60} className={field} /></label>
        <label className="font-black">Relocation<select name="relocationPreference" defaultValue={profile?.relocation_preference ?? "unsure"} className={field}><option value="stay-local">Prefer to stay local</option><option value="could-relocate">Could relocate</option><option value="unsure">Not sure yet</option></select></label>
        <label className="font-black">Routes to explore<select name="routeIntent" defaultValue={profile?.route_intent ?? "combined"} className={field}><option value="combined">University and apprenticeships</option><option value="university">University</option><option value="apprenticeship">Apprenticeships</option></select></label>
      </section>
      <fieldset className="rounded-[2rem] bg-white/80 p-5 shadow-sm sm:p-7"><legend className="px-1 text-xl font-black">Areas you want to explore</legend><div className="mt-4 grid gap-3 sm:grid-cols-4">{sectors.map((sector) => <label key={sector} className="flex min-h-14 cursor-pointer items-center gap-3 rounded-2xl border border-ink/10 bg-oat/70 px-4 font-black capitalize"><input type="checkbox" checked={selectedSectors.includes(sector)} onChange={(event) => setSelectedSectors((current) => event.target.checked ? [...current, sector] : current.filter((value) => value !== sector))} className="h-5 w-5 accent-leaf" />{sector}</label>)}</div></fieldset>
      <section className="space-y-5 rounded-[2rem] bg-white/80 p-5 shadow-sm sm:p-7"><div><h2 className="text-xl font-black">Qualifications</h2><p className="mt-2 text-sm font-semibold leading-6 text-ink/60">Each qualification is kept as a separate record. Routefinder can currently compare A-level and GCSE requirements deterministically; other types are saved but will need direct checking.</p></div><fieldset className="space-y-3"><legend className="font-black">Have you entered every qualification you want Routefinder to use for comparisons?</legend><p className="text-sm font-semibold leading-6 text-ink/60">If not, a qualification that is not entered stays unknown rather than being treated as absent.</p><label className="flex items-start gap-3 rounded-2xl border border-ink/10 bg-oat/60 p-4 font-semibold"><input required type="radio" name="qualificationsComplete" checked={qualificationsComplete === true} onChange={() => setQualificationsComplete(true)} className="mt-1 h-5 w-5 accent-leaf" /> <span>Yes, this record is complete for now.</span></label><label className="flex items-start gap-3 rounded-2xl border border-ink/10 bg-oat/60 p-4 font-semibold"><input required type="radio" name="qualificationsComplete" checked={qualificationsComplete === false} onChange={() => setQualificationsComplete(false)} className="mt-1 h-5 w-5 accent-leaf" /> <span>No, I will add more qualifications later.</span></label></fieldset>
      <div className="space-y-4">{qualifications.map((qualification, index) => { const rowId = qualification.id ?? `new-${index}`; const unknown = qualification.status === "unknown"; const unsupported = qualification.qualificationType.trim() && !["a level", "gcse"].includes(qualification.qualificationType.trim().toLowerCase()); return <fieldset key={rowId} className="rounded-2xl border border-ink/10 bg-oat/50 p-4"><legend className="px-1 font-black">Qualification {index + 1}</legend><div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">Qualification type<input required value={qualification.qualificationType} onChange={(event) => updateQualification(index, { qualificationType: event.target.value })} placeholder="A level, GCSE, BTEC…" className={field} /></label><label className="font-bold">Subject<input required value={qualification.subject} onChange={(event) => updateQualification(index, { subject: event.target.value })} placeholder="For example: Mathematics" className={field} /></label><label className="font-bold">Result status<select value={qualification.status} onChange={(event) => updateQualification(index, { status: event.target.value as QualificationRow["status"], ...(event.target.value === "unknown" ? { grade: "" } : {}) })} className={field}><option value="predicted">Predicted</option><option value="achieved">Achieved</option><option value="unknown">Unknown</option></select></label><label className="font-bold">Grade<input required={!unknown} disabled={unknown} value={qualification.grade} onChange={(event) => updateQualification(index, { grade: event.target.value })} placeholder={unknown ? "Not known yet" : "For example: A or 6"} className={`${field} disabled:cursor-not-allowed disabled:bg-ink/5`} /></label></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm font-semibold"><p className={unsupported ? "text-coral" : "text-ink/55"}>{unsupported ? "This qualification type is recorded, but Routefinder cannot compare it deterministically yet. Check relevant requirements directly." : "This type is within Routefinder’s current deterministic comparison vocabulary."}</p><button type="button" onClick={() => setQualifications((current) => current.filter((_, rowIndex) => rowIndex !== index))} className="min-h-11 rounded-full border border-ink/15 px-4 font-black">Remove</button></div></fieldset>; })}{!qualifications.length && <p className="rounded-2xl bg-sky p-4 text-sm font-semibold">No qualifications are recorded yet. You can save this as incomplete, or state that the record is complete if that accurately describes your information.</p>}<button type="button" onClick={() => setQualifications((current) => [...current, blankQualification()])} className="min-h-12 rounded-full border border-leaf px-5 font-black text-leaf">Add qualification</button></div>
      <label className="block font-black">Work styles you prefer<input name="workStyles" defaultValue={profile?.work_styles?.join(", ") ?? ""} placeholder="Practical, team-based, analytical" className={field} /></label><label className="block font-black">Financial preference<select name="financialPreference" defaultValue={profile?.financial_preference ?? "open"} className={field}><option value="open">Open to different options</option><option value="cost-aware">Cost is an important factor</option><option value="prefer-lower-debt">Prefer options with lower debt</option></select></label><label className="block font-black">Existing experience and responsibilities<textarea name="experienceSummary" rows={4} defaultValue={profile?.experience_summary ?? ""} maxLength={1000} placeholder="Projects, work, caring responsibilities, clubs, volunteering, or other experience you already have." className={field} /></label><label className="block font-black">Important constraints or unknowns<textarea name="constraints" rows={4} defaultValue={profile?.constraints?.join("\n") ?? ""} placeholder={"I am not sure whether I can relocate\nI need to check a predicted grade"} className={field} /></label></section>
      {message && <p role="alert" className="rounded-2xl bg-coral/10 p-4 font-bold text-ink">{message}</p>}<div className="flex flex-col items-start justify-between gap-4 rounded-[2rem] bg-ink p-5 text-white sm:flex-row sm:items-center sm:p-7"><p className="max-w-xl text-sm font-semibold leading-6 text-white/70">Your answers create a starting strategy. They do not rank routes or predict whether an application will succeed.</p><button disabled={saving || selectedSectors.length === 0 || qualificationsComplete === null} className="min-h-12 rounded-full bg-white px-6 font-black text-ink disabled:cursor-not-allowed disabled:opacity-50">{saving ? "Saving…" : "Save and find opportunities"}</button></div>
    </form>
  );
}
